### ISSUE TITLE
predictions_by_input not working

### ISSUE THREAD

**Issue by atinder** [qpowell/google_places#103]
```
@client = GooglePlaces::Client.new(API_KEY)

@client.predictions_by_input(
    'San F',
    lat: 0.0,
    lng: 0.0,
    radius: 20000000,
    types: 'geocode',
    language: I18n.locale,
)
```

undefined method `predictions_by_input' for #<GooglePlaces::Client:0x0000000625bcb8>

**Comment by atinder** [comment]
I tried using the code from master branch and it worked.
Is there any release planned for this change ?

**Comment by edwinwills** [comment]
Master branch is `v0.34.2` that's live on RubyGems now - https://rubygems.org/gems/google_places/

I just tried installing this gem fresh from RubyGems and running the code you pasted above, and it works fine.

In your directory with the broken GooglePlaces app, mind running `gem list | grep google_places` to see which version you've got installed?

**Comment by atinder** [comment]
I didn't specify any version while installing this. Just added `gem 'google_places' `into my gem file.
Found out that version 0.21.0 is installed. I had to manually specify `gem 'google_places', '~> 0.34.2'` for it to work

**Comment by edwinwills** [comment]
Hmm - might be a problem with local cached version of rubygems, but if you do a clean install, rubygems should install the latest version of any published gem.

**Comment by atinder** [comment]
yea, maybe. You can close the issue, sorry for the noise. Might be helpful for someone googling this.

**Comment by edwinwills** [comment]
All good - thanks!
