### ISSUE TITLE
Httparty at version 0.15.6

### ISSUE THREAD

**Issue by michaelminter** [qpowell/google_places#104]

**Comment by edwinwills** [comment]
Just had a quick go at upgrading, httparty 0.15.6 requires Ruby >= 2.0, and the google_places gem currently supports 1.9.3 and up.

@qpowell what do you think of dropping 1.9.3 support and pushing a 1.0.0 release, as 1.9.3 has been EOL for a while? Happy to push up a PR if you agree.

**Comment by qpowell** [comment]
@edwinwills I think a 1.0.0 release that drops 1.9.3 support is a good idea :)

**Comment by edwinwills** [comment]
Sorry for the delay - PR up now https://github.com/qpowell/google_places/pull/105

**Comment by edwinwills** [comment]
@michaelminter v1.0.0 now pushed with upgraded httparty gem
