### ISSUE TITLE
Add fields option to spots search with detail

### ISSUE THREAD

**Issue by dalton-cole** [qpowell/google_places#130]
Current a spots search with detail will pull all fields with no way to limit them. This can get expensive.

**Comment by richardsondx** [comment]
@dalton-cole Did you find a solution for this? I'm currently looking for a solution.

**Comment by richardsondx** [comment]
Solution is In the README
```
To only retrieve specific fields for an individual spot, use a comma delimited string of acceptable fields @client.spot(place_id, fields:'place_id,name')
```

**Comment by dalton-cole** [comment]
@richardsondx, yes I did. Same as you, forgot to close this out.
