### ISSUE TITLE
spots_by_bounds does not return results within bounds

### ISSUE THREAD

**Issue by gbuesing** [qpowell/google_places#82]
I can't get #spots_by_bounds to actually query within a supplied bounding box. I don't think the Google API currently supports this feature.

I tried actually running the stubbed out example from the specs, and that doesn't work as expected, it just returns results from around the US, none in the supplied bounding box: https://gist.github.com/gbuesing/a28932ac8dcb64c5bcf6

Nor can I find any mention of a bounds parameter in the Google Places API documentation: https://developers.google.com/places/web-service/search#TextSearchRequests . It does appear to be a feature of the client-side JS library, but not the server-side API.

I notice that this feature was added in February: https://github.com/marceldegraaf/google_places/pull/74 . Did Google change the API since then?

Can anybody else get this to actually work? If not, I'd be happy to pull together a pull request that drops this no-longer supported feature.

**Comment by gbuesing** [comment]
CC @TNCodeMonkey - does this feature work for you anymore?

**Comment by qpowell** [comment]
@gbuesing Sorry for the delayed response, I recently took over maintenance of this gem so I'll have a look. I think Google has a habit of changing these things on the fly (see #64) but I haven't been able to find a reliable way to stay up to date with these changes. They don't seem to publish changelogs or release notes for the web service like they do with the client library :cry: 

It would be awesome if you could put together a pull request to drop the feature. In the near future I'll be doing an audit to see if there are any other features that they've ripped out support for.

Thanks!

**Comment by TNCodeMonkey** [comment]
I just received the message for this issue.  I pulled down the most recent version and should hopefully have an answer soon.

**Comment by TNCodeMonkey** [comment]
@gbuesing , if you look under the "Option Parameters" section (https://developers.google.com/places/web-service/search#TextSearchRequests)

location — The latitude/longitude around which to retrieve place information. This must be specified as latitude,longitude. If you specify a location parameter, you must also specify a radius parameter.

**Comment by gbuesing** [comment]
@TNCodeMonkey just pinging to see if you were able to figure anything out on this. I ran my test gist again, and the api is still not respecting the supplied bounding box.
