### ISSUE TITLE
No "profile_photo_url" in review

### ISSUE THREAD

**Issue by sergykorets** [qpowell/google_places#92]
I do not see "profile_photo_url" in <GooglePlaces::Review> as it is in original response from Google places API. May you add it?
`#<GooglePlaces::Review:0x007fb9462e2640 @rating=5, @type=nil, @author_name="Таня ЯЯ", @author_url="https://www.google.com/maps/contrib/102709091342507193601/reviews", @text="", @time=1474563857>`

**Comment by edwinwills** [comment]
Have just added this to the latest release (v1.1.0)
