### ISSUE TITLE
Argument Error

### ISSUE THREAD

**Issue by kojha31** [qpowell/google_places#97]
@client.spot(@place_id) throws a argument error for some of the place ids

**Comment by edwinwills** [comment]
Mind adding an example of a place id that throws an argument error?

**Comment by cgunther** [comment]
I believe I'm seeing the same error after upgrading to v0.34.0 as I did not encounter an error on v0.33.0.

The exact error I get is:
`ArgumentError: wrong number of arguments (given 6, expected 7)`

The backtrace is:
```
google_places-0.34.0/lib/google_places/review.rb:6:in `initialize'
google_places-0.34.0/lib/google_places/spot.rb:464:in `new'
google_places-0.34.0/lib/google_places/spot.rb:464:in `block in reviews_component'
google_places-0.34.0/lib/google_places/spot.rb:463:in `map'
google_places-0.34.0/lib/google_places/spot.rb:463:in `reviews_component'
google_places-0.34.0/lib/google_places/spot.rb:440:in `initialize'
google_places-0.34.0/lib/google_places/spot.rb:258:in `new'
google_places-0.34.0/lib/google_places/spot.rb:258:in `find'
google_places-0.34.0/lib/google_places/client.rb:117:in `spot'
```

My calling code is:
```ruby
GooglePlaces::Client.new("<MY-API-KEY>").spot("<THE-ID>")
```

Here's where I can't make sense of it. Line 6 of the Review class when viewing the v0.34.0 tag on GitHub is not the definition of the initialize method and clearly only expected 6 arguments, not 7 as the error suggests:
https://github.com/qpowell/google_places/blob/0.34.0/lib/google_places/review.rb#L6

If I download the gem directly from RubyGems.org (https://rubygems.org/downloads/google_places-0.34.0.gem) and extract the gem archive then the inner data archive and view the Review class, I see the following definition:

```ruby
module GooglePlaces
  class Review
    attr_accessor :rating, :type, :author_name, :author_url, :text, :time,
                  :profile_photo_url

    def initialize(rating, type, author_name, author_url, text, time, profile_photo_url)
      @rating            = rating
      @type              = type
      @author_name       = author_name
      @author_url        = author_url
      @text              = text
      @time              = time
      @profile_photo_url = profile_photo_url
    end
  end
end
```

Notice the extra `profile_photo_url` argument which is not included at the GitHub tag. It seems the Review class included in the gem archive is not the same Review class included in the git repo, hence the error.

Could it be that when building the gem archive, a change to the Review class was either included by accident, or forgot to be committed/pushed to GitHub?

**Comment by edwinwills** [comment]
Ah I'm an idiot - was playing about with some new features (uncommited) when I built. Will build 0.34.1 and push now.

**Comment by edwinwills** [comment]
Fixed and pushed now - apologies for this

**Comment by cgunther** [comment]
Terrific, that fixed it. Thanks for the quick turnaround.
