### ISSUE TITLE
Prediction object doesn't set all of the fields

### ISSUE THREAD

**Issue by johnmosesman** [qpowell/google_places#99]
The [Prediction initialize method](https://github.com/qpowell/google_places/blob/master/lib/google_places/prediction.rb#L11) doesn't set all of the fields from the result—namely the `structured_formatting` fields:

![image](https://user-images.githubusercontent.com/3760568/27975523-1cb29c5c-6328-11e7-982b-83172e10fc38.png)

Can these be added to the initializer?

**Comment by edwinwills** [comment]
Hey @johnmosesman! I've just added this attribute + `matched_substrings` to the Prediction class - in master here, and pushed as a new version to RubyGems now - PR over at https://github.com/qpowell/google_places/pull/100
